# Generated by Django 3.2.4 on 2021-07-24 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('psid', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Error', 'Error'), ('Warning', 'Warning'), ('Undefined', 'Undefined'), ('Ok', 'Ok')], default='Undefined', max_length=20)),
                ('server', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['psid'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='images/default_user_img.png', upload_to='')),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, max_length=20, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Error', 'Error'), ('Warning', 'Warning'), ('Undefined', 'Undefined'), ('Ok', 'Ok')], max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logchecker.district')),
            ],
        ),
    ]
