# Generated by Django 3.2.4 on 2021-06-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logchecker', '0004_alter_district_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
