# Generated by Django 3.2.4 on 2021-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logchecker', '0006_alter_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='psid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
